### PR TITLE
Working p2p video calling with no frontend framework

### PR DESCRIPTION
**Pull request by dalyIsaac**
This is a simple server and client.

If you go to `/`, you will be served `join.html` (which is a bit empty at this point).

If you go to `/:roomId`, where `roomId` is any string, you can join a room.

**Changes**:

- Creating rooms has been moved to a REST-based approach - there is now only a single web socket, for peerjs (as suggested by @Ishan27g)
- The code has been moved to a class-based approach, which should be easier to understand.
- The client only relies on peerjs, which is provided the unpkg CDN

**Yet to be implemented**:

- handling broken connections

### CODE REVIEW

**Review by Ishan27g — APPROVED** [review]
Looks good. I tried it out, I don't see any 'video' though, just the text "Hello room!"

**Comment by Ishan27g** [comment]
Is `/:roomId` handling both the creation or joining of a room depending on its existence? I'm not sure how room creation is happening. 

Review my PR before merging this PR

**Comment by dalyIsaac** [comment]
> Is `/:roomId` handling both the creation or joining of a room depending on its existence? I'm not sure how room creation is happening.

From the client's point of view, they're joining a room. They're not aware that the room has yet to be created: https://github.com/zoomutex/zoomutex/blob/203dd60e53d7a964e482b59762ae06449ee1e700/client/scripts/room.ts#L64-L84

From the server's point of view, once it receives a request for a room, it tries to get the peers from the room, given the `roomId`: https://github.com/zoomutex/zoomutex/blob/203dd60e53d7a964e482b59762ae06449ee1e700/server/server.ts#L29-L41

If the room does not exist, it is created. The response to the message is the peers currently in the room: https://github.com/zoomutex/zoomutex/blob/203dd60e53d7a964e482b59762ae06449ee1e700/server/rooms.ts#L24-L49

**Comment by dalyIsaac** [comment]
> Looks good. I tried it out, I don't see any 'video' though, just the text "Hello room!"

That's strange - it definitely works on my machine. You might need to check the permissions available for the page:

image

(At least that's what it looks like in my browser.)

**Pull request merged**
